Función Insert sobre KVstore sin validación de claves.
uandes-icc3201-201920/tarea-1-cefunck-naespinola pull request #1
Opened 2019-09-02 21:15 UTC by cefunck

Implementé una función insert con el objetivo de guardar datos string en el almacenamiento KV.

La función recibe parámetros unsigned long key y string data, este último se utiliza para crear el vector de bytes que es necesario para crear el Value que es insertado en el almacenamiento KV.

Por ahora no se ha implementado la validación de claves.

2019-09-02 22:31 UTC, NataliaEspinola requested changes

2019-09-02 22:31 UTC, NataliaEspinola commented on server.cpp
> +	db.insert(std::pair<unsigned long, Value>(key, value));
No es necesario poner std:: ya que mas arriba, en la linea 8, esta puesto el `using namespace std;`

2019-09-02 22:31 UTC, NataliaEspinola commented on server.cpp
> +int insert(unsigned long key, string data){
El nombre de la función `insert` podría causar algunos errores mas adelante. Ya que existe otra función llamada de la misma manera para map.

2019-09-03 17:56 UTC, cefunck commented on server.cpp
> +	db.insert(std::pair<unsigned long, Value>(key, value));
ok, sacado en el nuevo commit :)

2019-09-03 17:57 UTC, cefunck commented on server.cpp
> +int insert(unsigned long key, string data){
ok, ahora se llama `insert_into_db` :)

2019-09-03 17:58 UTC, merged